### ISSUE TITLE
Upgrade to 7.1

### ISSUE THREAD

**Issue by netlander** [krishnaapatel/CustomAuthPipeline#1]
Any chance this project can be upgraded to Liferay 7.1?

**Comment by krishnaapatel** [comment]
I have updated project for 7.1 ([v2.0](https://github.com/krishnaapatel/CustomAuthPipeline/tree/v2.0)). Any change requests are welcome.

**Comment by netlander** [comment]
I don't believe there is action taken about this issue which I have forgotten about so long ago.

BTW I have also moved on from Liferay entirely, I think the Liferay Portal project is a joke.
